DELIMITER ;
CREATE DATABASE IF NOT EXISTS Employees;
use Employees;
DROP  TABLE IF EXISTS EMPINFO;
DROP  TABLE IF EXISTS DEPT;
DROP  TABLE IF EXISTS EDUDETAILS;
DROP  TABLE IF EXISTS ADDRESS;

CREATE TABLE EMPINFO
(EMPID INT(4) NOT NULL AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME varchar(10),
MIDDLE_NAME varchar(10),
LAST_NAME varchar(10),
DESIGNATION varchar(10),
DEPT_ID INT ,
FOREIGN KEY (DEPT_ID)
		REFERENCES DEPT(DEPTID)
        ON DELETE CASCADE,
DATE_OF_BIRTH  date,
JOINING_DATE date,
GENDER varchar(10),
PASSWORD varchar(30),
ROLE varchar(10),
EMAIL varchar(30),
MOBILE_NO INT(12),
ADHAAR_NO INT(14),
PERFORMANCE varchar(20),
SALARY DECIMAL(10,2));

INSERT INTO EMPINFO VALUES
	
		(0001,'Monika', 'Aman' 'Arora', 'Trainee', 1001, '14-02-90 ', '20-1-10','Female','1234','Admin', 'monika@gmail.com', 9586434856,456878953458,'Good',15000),
		(0002,'Snehal', 'Karan' 'Sharma', 'System Engineer', 1003, '18-03-92 ', '14-02-18','Female','456','User', 'snehal@gmail.com', 8745485612,484865758973,'ok',8000);



CREATE TABLE DEPT
       (DEPTID INT(4) NOT NULL PRIMARY KEY,
        DEPTNAME varchar(20));

INSERT INTO DEPT VALUES
        (1001, 'HR');
INSERT INTO DEPT VALUES
        (1002, 'SALES');
INSERT INTO DEPT VALUES
         (1003, 'CUSTOMER SUPPORT');
INSERT INTO DEPT VALUES
         (1004, 'RND');
         
CREATE TABLE EDUDETAILS
       (EMP_ID INT,
       FOREIGN KEY (EMP_ID)
		REFERENCES EMPINFO(EMPID)
        ON DELETE CASCADE,
	   10_TH DECIMAL(10,2),
       HSC DECIMAL(10, 2),
       DIPLOMA DECIMAL(10,2),
       DEGREE DECIMAL(10,2),
       POST_GRADUATION DECIMAL(10,2),
       PHD DECIMAL(10,2));
       

INSERT INTO EDUDETAILS VALUES
        (0001, 90.8, 85.7,NULL,72.8,NULL,NULL),
        (0002, 80.8, NULL,75,62.8,70,NULL);

         
CREATE TABLE ADDRESS
       (EMP_ID INT,
       FOREIGN KEY (EMP_ID)
		REFERENCES EMPINFO(EMPID)
        ON DELETE CASCADE,
        HOUSE_NO varchar(20),
         STREET varchar(20),
          CITY varchar(20),
           STATE varchar(20),
            COUNTRY varchar(20),
            PINCODE int(8));
            

INSERT INTO ADDRESS VALUES
        (0001, '3',  'Santacruz','MUMBAI','MAHARASHTRA','INDIA',400054),
        (0002, '8',  'BANDRA','MUMBAI','MAHARASHTRA','INDIA',400050);

         
CREATE TABLE DUMMY
        (DUMMY INT);

INSERT INTO DUMMY VALUES (0);

COMMIT;
DELIMITER ;
